config/routes.rb
Rails.application.routes.draw do
  # landing and users resources
  root 'users#new'
  get '/users' => 'users#new', as: 'users'
  post '/users' => 'users#create', as: 'create_users'

  # resources :users

  # handle connections and connections list for admin
  get '/connections' => 'connections#connections'
  get '/connections/list' => 'connections#list'

  # handles omniauth
  get '/auth/:provider' => 'connections#omniauth', as: 'auth_login'
  match '/auth/:provider/callback' => 'connections#omniauth', via: [:get, :post]

  # handles login view and auth
  get '/login' => 'sessions#login_user'
  post '/login' => 'sessions#auth'

  # handles admin login
  get '/login/admin' => 'sessions#login_admin'
  post '/login/admin' => 'sessions#auth'

  # destroy sessions
  get '/logout' => 'sessions#destroy'
end

app/models/connection.rb
class Connection < ActiveRecord::Base
  belongs_to :users
end

app/models/session.rb
class Session < ActiveRecord::Base
  has_no_table
  attr_accessor :email, :password, :string
  validates :email, presence: true,
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates_presence_of :password, if: -> { self.password }
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, :email, presence: true
  validates :name, length: { minimum: 2, maximum: 20 }
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
  validates_uniqueness_of :email
  # has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # helper modules for authorizing
  helper_method :current_user
  helper_method :user_signed_in?
  helper_method :admin?
  helper_method :authorize!
  helper_method :authorize_admin_only!

  private

  # current user
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  # check if user is logged in
  def user_signed_in?
    return true if current_user
  end

  # check if logged in user is admin?
  def admin?
    return true if session[:is_admin]
  end

  # redirect to login
  def authorize!
    redirect_to '/login' unless current_user
  end

  # check if authorized
  def authorized?
    redirect_to '/connections' if current_user
  end

  # only admins stuff
  def authorize_admin_only!
    redirect_to '/login' unless admin?
  end
end

app/controllers/connections_controller.rb
class ConnectionsController < ApplicationController
  # connections and omniauth requires user logged in
  before_filter :authorize!, only: [:connections, :omniauth]

  # list require an admin
  before_filter :authorize_admin_only!, only: [:list]

  # omniauth callback
  def omniauth
    render json: request.env['omniauth.auth']
  end

  # admin list of all users
  def list
    @users = User.all
  end

  # view for connections
  def connections
  end

  private

  # save method for the connection
  def save_connection(type, url, data)
  end

  # cure facebook data
  def facebook_data
  end

  # cure twitter data
  def twitter_data
  end

  # cure linkedin data
  def linkedin_data
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # authorized
  before_filter :authorized?, only: [:login_user]
  before_action :set_session, only: [:login_user, :login_admin]

  # login user view
  def login
  end

  # admin user view
  def login_admin
  end

  # authorize users by email only
  def auth
    params = user_params
    type = params[:password].nil? ? 'user' : 'admin'
    @session = Session.new(params)
    if @session.valid?
      send("auth_#{type}", params)
    else
      render "login_#{type}".to_sym
    end
  end

  # destroy sessions
  def destroy
    session[:user_id]  = nil
    session[:is_admin] = nil
    redirect_to '/'
  end

  private

  def set_session
    @session = Session.new
  end

  def auth_user(params)
    user = User.find_by_email(params[:email])
    session[:tmp] = user
    if user
      session[:user_id] = user.id
      redirect_to '/connections'
    else
      render :login_user
    end
  end

  def auth_admin(params)
    user = User.find_by(email: params[:email], admin: true)
    if user && params[:password] == 'admin'
      session[:user_id]  = user.id
      session[:is_admin] = true
      redirect_to '/connections/list'
    else
      render :login_admin
    end
  end

  # filter stuff
  def user_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # common filters to access resources
  before_filter :authorized?, only: [:new]
  before_action :new_user, only: [:new]

  # GET /users/new
  def new
  end

  # POST /users
  # save user in db
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to '/connections'
    else
      render :new
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def new_user
    @user = User.new
  end

  # Never trust parameters from the scary internet,
  # only allow the white list through.
  def user_params
    params.require(:user).permit(:name, :email)
  end

  # make random password
  def make_password
    Array.new(10) { [*'A'..'Z', *'a'..'z', *'0'..'9'].sample }.join
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_class(*path)
    in_path?(*path) ? 'active' : ''
  end

  def in_path?(*routes)
    routes.select { |item| item == request.fullpath }.length > 0
  end
end

app/views/connections/connections.html.erb
<div class="jumbotron text-center">
  <div class="container">
    <div class="col-md-12">
      <h2>Connections</h2>
      <div class="col-md-4">
        <a href="/auth/facebook">Facebook</a>
      </div>
      <div class="col-md-4">
      <a href="/auth/twitter">Twitter</a>
      </div>
      <div class="col-md-4">
      <a href="/auth/linkedin">Linkedin</a>
      </div>
    </div>
  </div>
</div>

app/views/connections/list.html.erb
<div class="jumbotron ">
  <div class="container">
    <div class="col-md-12">
    <h4>Listing Users</h4>
    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th colspan="3"></th>
          <th>Email</th>
          <th colspan="3"></th>
          <th colspan="3"></th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= user.name %></td>
            <th colspan="3"></th>
            <td><%= user.email %></td>
            <th colspan="3"></th>

            <td><%= link_to 'Show', user %></td>
            <th colspan="3"></th>
            <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<div class="page-header">
  <div class="header">
    <ul class="nav nav-pills pull-right">
        <% if user_signed_in? %>
        <li class="disabled">
            <a style="cursor:default">
                <b>Logged in as <%=  admin? ? 'Administrador' : current_user['name']%></b>
            </a>
        </li>
        <li class="<%= active_class('/connections') %>"><%= link_to 'My Connections', connections_path %></li>
        <% if admin? %>
            <li class="<%= active_class('/connections/list') %>"><%= link_to 'Users', connections_list_path %></li>
        <% end %>
        <li class="<%= active_class('/logout') %>"><%= link_to 'logout', logout_path %></li>
        <% else %>
        <li class="<%= active_class('/', '/users') %>"><%= link_to 'Home', root_path %></li>
        <li class="<%= active_class('/login') %>"><%= link_to 'Login', login_path %></li>
    <% end %>
    </ul>
    <h3 class="text-muted">Social</h3>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Social</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="main-container" class="container">
    <%= render '/layouts/header' %>
    <div class="row">
      <div class="col-md-12">
        <%= yield %>
      </div>
    </div>
  <%= debug(params) if Rails.env.development? %>
  </div>
</body>
</html>

app/views/users/_form.html.erb
<div id="new_user">
  <%= simple_form_for(@user) do |f| %>
    <div class="form-group">
      <div class="col-sm-8">
        <%= f.input :name, placeholder: 'Name', error: 'Invalid Name', label: false %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-sm-8">
        <%= f.input :email, placeholder: 'Email', label: false %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-sm-8">
        <%= f.button :submit, 'Sign Up', class: 'btn-info' %>
      </div>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Password</th>
      <th>Active</th>
      <th>Admin</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= user.active %></td>
        <td><%= user.admin %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div class="jumbotron text-center">
  <div class="container">
    <div class="col-md-9 col-md-offset-3">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="jumbotron ">
  <div class="container">
    <div class="col-md-12">
      <p>
        <strong>Name:</strong>
        <%= @user.name %>
      </p>

      <p>
        <strong>Email:</strong>
        <%= @user.email %>
      </p>
      <p>
        <strong>Connections:</strong>
        12
      </p>

      <%= link_to 'Back', connections_list_path %>
    </div>
  </div>
</div>